scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ["app:8000"]

  - job_name: proxy
    scrape_interval: 5s
    static_configs:
      - targets: ["proxy-exporter:9113"]
